// =================================================================================
// REPLICATION SERVICE (The Distribution Coordinator)
// =================================================================================
// This service manages the parallel propagation of HLS assets.
// It ensures high availability by streaming segments to multiple
// regional storage nodes across the cluster.
// =================================================================================

import { Injectable, Logger } from '@nestjs/common';
import axios from 'axios';
import axiosRetry from 'axios-retry';
import FormData from 'form-data';
import * as fs from 'fs';
import * as path from 'path';

// [RESILIENCE] Global retry configuration for backend storage operations
axiosRetry(axios, {
  retries: 5,
  retryDelay: axiosRetry.exponentialDelay,
  retryCondition: (error) => {
    return axiosRetry.isNetworkOrIdempotentRequestError(error) || 
           !!(error.response && error.response.status >= 500);
  },
});

@Injectable()
export class ReplicationService {
  private readonly logger = new Logger(ReplicationService.name);
  
  // [NESTJS] Configuration-driven storage node topology
  private readonly storageNodes = [
    process.env.STORAGE_NODE_A || 'http://storage-node-a:4001',
    process.env.STORAGE_NODE_B || 'http://storage-node-b:4001',
    process.env.STORAGE_NODE_C || 'http://storage-node-c:4001',
  ];

  // REPLICATE: Orchestrates high-availability data distribution
  async replicate(videoId: string, hlsDir: string): Promise<string[]> {
    // 1. [VALIDATION] List all segments generated by transcoding
    const files = fs.readdirSync(hlsDir);
    const successfulNodes: string[] = [];

    // 2. [PERFORMANCE] Trigger parallel replication to primary nodes (A & B)
    // Why: Ensures at least two copies exist before marking the job as complete
    const primaryReplication = [
        this.replicateToNode(this.storageNodes[0], videoId, hlsDir, files),
        this.replicateToNode(this.storageNodes[1], videoId, hlsDir, files),
    ];

    // 3. [SIDE EFFECT] Wait for primary nodes to confirm storage
    const results = await Promise.allSettled(primaryReplication);
    
    if (results[0].status === 'fulfilled') successfulNodes.push('A');
    if (results[1].status === 'fulfilled') successfulNodes.push('B');

    // 4. [SIDE EFFECT] Fire-and-forget backup to secondary node (C)
    // Non-blocking so we don't delay the main API response
    this.replicateToNode(this.storageNodes[2], videoId, hlsDir, files)
        .then(() => successfulNodes.push('C'))
        .catch(err => this.logger.error(`Backup replication to Node C failed: ${err.message}`));

    return successfulNodes;
  }

  // REPLICATE TO NODE: Performs multi-part upload of HLS assets to a single node
  private async replicateToNode(nodeUrl: string, videoId: string, hlsDir: string, files: string[]) {
    this.logger.log(`Replicating video ${videoId} to ${nodeUrl}`);
    
    // 1. [PERFORMANCE] Batch upload segments to the target storage node
    // Why: Parallelizing transfers reduces latency for videos with many HLS chunks
    const BATCH_SIZE = 5;
    for (let i = 0; i < files.length; i += BATCH_SIZE) {
      const batch = files.slice(i, i + BATCH_SIZE);
      
      await Promise.all(batch.map(async (file) => {
        const filePath = path.join(hlsDir, file);
        const formData = new FormData();
        formData.append('videoId', videoId);
        formData.append('file', fs.createReadStream(filePath));

        await axios.post(`${nodeUrl}/store`, formData, {
          headers: formData.getHeaders(),
          timeout: 60000, // Increased to 60s for high-concurrency scenarios
        });
      }));
    }
    
    this.logger.log(`Successfully replicated ${videoId} to ${nodeUrl}`);
  }
}
